#!/usr/bin/env bash
set -x

pid=0

term_handler() {
	if [ $pid -ne 0 ]; then
		kill -SIGTERM "$pid"
		wait "$pid"
	fi
	exit 143;  # 128 + 15 -- SIGTERM
}

trap 'term_handler' SIGTERM SIGINT SIGKILL

ansible-playbook playbooks/01.run.pg.yml &
pid="$!"

# exec "$@"
while true
do
	tail -f /dev/null & wait ${!}
done